//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webthanhtamstore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THANHTAMSTOREEntities1 : DbContext
    {
        public THANHTAMSTOREEntities1()
            : base("name=THANHTAMSTOREEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUDE> CHUDEs { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<DONHANGGG> DONHANGGGs { get; set; }
        public virtual DbSet<KHACHHANGGG> KHACHHANGGGs { get; set; }
        public virtual DbSet<CHITIETDONHANGGGG> CHITIETDONHANGGGGs { get; set; }
    }
}
